- name: add erlang repository
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
  become: yes

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install erlang
  apt:
    name: esl-erlang
    state: present
  become: yes

- name: install elixir
  apt:
    name: elixir
    state: present
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

